<?php
/**
 * @var \Core\Models\Data\DataCollection $data
 */

/**
 * @var \Core\View\PageRenderer $this
 */

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $data->getTitle() ?? "Homepage" ?></title>
    <?php
        /**
         * @var \Core\Tags\LinkTag $tag
         */
        foreach ($this->linkTags as $link) {
            $link->render();
        }
?>

    <?php
    /**
     * @var \Core\Tags\MetaTag $tag
     */
    foreach ($this->metaTags as $tag) {
        $tag->render();
    }
?>

    <?php
    /**
     * @var \Core\Tags\ScriptTag $script
     */
    foreach ($this->scriptTags as $script) {
        $script->render();
    }
    ?>
    <!-- Favicon -->
    <link rel="icon" href="/favicon.ico">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="<?= \Core\Helpers\ViewHelper::getMainStylesheet() ?>">

    <!-- JS at top only if absolutely needed -->
</head>
<body class="bg-gray-100 text-gray-800 antialiased">
<?= $this->include("Partial/header") ?>
<?php
/** @var  $template */
echo $template;
?>
<?= $this->include("Partial/footer") ?>
</body>
</html>
