<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $title ?? "Homepage" ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <?php
        if (isset($metaTags)) {
            /**
             * @var \Core\Tags\MetaTag $tag
             */
            foreach ($metaTags as $tag) {
                $tag->render();
            }
        }
    ?>

    <?php
    if (isset($scripts)) {
        /**
         * @var \Core\Tags\ScriptTag $tag
         */
        foreach ($scripts as $script) {
            $script->render();
        }
    }
    ?>

    <!-- Favicon -->
    <link rel="icon" href="/favicon.ico">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="styles.css">

    <!-- JS at top only if absolutely needed -->
</head>
<body>
<?php
    /** @var  $template */
    echo $template;
?>
</body>
</html>
